"""authors

Revision ID: 07b7ba689538
Revises: e65fa0d599ae
Create Date: 2025-11-26 20:11:17.926914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "07b7ba689538"
down_revision: Union[str, Sequence[str], None] = "e65fa0d599ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "article_authors",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.drop_column("article_authors", "position")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "article_authors",
        sa.Column("position", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("article_authors", "created_at")
    # ### end Alembic commands ###
