"""Initial migration

Revision ID: 0b3aed08d303
Revises: 
Create Date: 2025-08-12 13:44:09.439987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3aed08d303'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('affiliation_clarification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliation_id', sa.Uuid(), nullable=False),
    sa.Column('faculty', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affiliations_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliation_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affiliations_aliases')
    op.drop_table('affiliation_clarification')
    op.drop_table('affiliations')
    # ### end Alembic commands ###
