"""Authors

Revision ID: 1883b31fc2fd
Revises: 812902d62ee3
Create Date: 2025-08-13 10:06:06.666851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1883b31fc2fd'
down_revision: Union[str, Sequence[str], None] = '812902d62ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('scopus_id', sa.String(), nullable=False),
    sa.Column('orcid_id', sa.String(), nullable=False),
    sa.Column('affiliation_id', sa.Uuid(), nullable=False),
    sa.Column('affiliation_clarification', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['affiliation_clarification'], ['affiliation_clarification.id'], ),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors')
    # ### end Alembic commands ###
