"""cascade

Revision ID: 228c1ef06fec
Revises: 2ea464d594dc
Create Date: 2025-09-19 19:14:43.215527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228c1ef06fec'
down_revision: Union[str, Sequence[str], None] = '2ea464d594dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('authors_affiliations_author_id_fkey'), 'authors_affiliations', type_='foreignkey')
    op.create_foreign_key(None, 'authors_affiliations', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('proceeding_volume_articles_article_id_fkey'), 'proceeding_volume_articles', type_='foreignkey')
    op.drop_constraint(op.f('proceeding_volume_articles_proceeding_volume_id_fkey'), 'proceeding_volume_articles', type_='foreignkey')
    op.create_foreign_key(None, 'proceeding_volume_articles', 'articles', ['article_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'proceeding_volume_articles', 'proceeding_volume', ['proceeding_volume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proceeding_volume_articles', type_='foreignkey')
    op.drop_constraint(None, 'proceeding_volume_articles', type_='foreignkey')
    op.create_foreign_key(op.f('proceeding_volume_articles_proceeding_volume_id_fkey'), 'proceeding_volume_articles', 'proceeding_volume', ['proceeding_volume_id'], ['id'])
    op.create_foreign_key(op.f('proceeding_volume_articles_article_id_fkey'), 'proceeding_volume_articles', 'articles', ['article_id'], ['id'], onupdate='CASCADE')
    op.drop_constraint(None, 'authors_affiliations', type_='foreignkey')
    op.create_foreign_key(op.f('authors_affiliations_author_id_fkey'), 'authors_affiliations', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###
