"""editorial

Revision ID: 28676ac61a94
Revises: 7252d683b960
Create Date: 2025-08-29 14:10:30.503502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28676ac61a94'
down_revision: Union[str, Sequence[str], None] = '7252d683b960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('articles', sa.Column('editorial', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'editorial')
    # ### end Alembic commands ###
