"""proceedings

Revision ID: 2b1c7b4655b2
Revises: 9ea747adda5c
Create Date: 2025-08-31 12:35:08.271697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1c7b4655b2'
down_revision: Union[str, Sequence[str], None] = '9ea747adda5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proceedings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('proceeding_volume', sa.Column('proceeding_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'proceeding_volume', 'proceedings', ['proceeding_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proceeding_volume', type_='foreignkey')
    op.drop_column('proceeding_volume', 'proceeding_id')
    op.drop_table('proceedings')
    # ### end Alembic commands ###
