"""unique article authors

Revision ID: 2ea464d594dc
Revises: d61bcc5fe71b
Create Date: 2025-09-14 19:30:28.434044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea464d594dc'
down_revision: Union[str, Sequence[str], None] = 'd61bcc5fe71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_article_author', 'article_authors', ['article_id', 'author_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_article_author', 'article_authors', type_='unique')
    # ### end Alembic commands ###
