"""added city

Revision ID: 34ede3b76541
Revises: 5680189d6f11
Create Date: 2025-10-21 11:49:15.843579

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34ede3b76541"
down_revision: Union[str, Sequence[str], None] = "5680189d6f11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "affiliations",
        sa.Column("city", sa.String(), nullable=False, server_default="City"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("affiliations", "city")
    # ### end Alembic commands ###
