"""cascading

Revision ID: 4ec2c083003f
Revises: ea93f5022e5e
Create Date: 2025-09-11 14:23:18.017660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec2c083003f'
down_revision: Union[str, Sequence[str], None] = 'ea93f5022e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('article_authors_article_id_fkey'), 'article_authors', type_='foreignkey')
    op.create_foreign_key(None, 'article_authors', 'articles', ['article_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('proceeding_volume_articles_article_id_fkey'), 'proceeding_volume_articles', type_='foreignkey')
    op.create_foreign_key(None, 'proceeding_volume_articles', 'articles', ['article_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proceeding_volume_articles', type_='foreignkey')
    op.create_foreign_key(op.f('proceeding_volume_articles_article_id_fkey'), 'proceeding_volume_articles', 'articles', ['article_id'], ['id'])
    op.drop_constraint(None, 'article_authors', type_='foreignkey')
    op.create_foreign_key(op.f('article_authors_article_id_fkey'), 'article_authors', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
