"""files

Revision ID: 571df5b81e4f
Revises: eb5c73a4d264
Create Date: 2025-08-14 20:11:46.757115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571df5b81e4f'
down_revision: Union[str, Sequence[str], None] = 'eb5c73a4d264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('stored_name', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('size_bytes', sa.BIGINT(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('articles', sa.Column('doi', sa.String(), nullable=False))
    op.add_column('articles', sa.Column('pdf_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'articles', 'files', ['pdf_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'pdf_id')
    op.drop_column('articles', 'doi')
    op.drop_table('files')
    # ### end Alembic commands ###
