"""volume

Revision ID: 7252d683b960
Revises: 764187d423b8
Create Date: 2025-08-29 13:54:48.532013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7252d683b960'
down_revision: Union[str, Sequence[str], None] = '764187d423b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proceeding_volume', sa.Column('published_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proceeding_volume', 'published_at')
    # ### end Alembic commands ###
