"""pages

Revision ID: 764187d423b8
Revises: bf9234d67ecb
Create Date: 2025-08-29 11:56:07.623686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764187d423b8'
down_revision: Union[str, Sequence[str], None] = 'bf9234d67ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('pages_in_volume', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'pages_in_volume')
    # ### end Alembic commands ###
