"""articles fix

Revision ID: 7e851d742ae3
Revises: e2fee546c754
Create Date: 2025-08-26 11:23:15.418385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e851d742ae3'
down_revision: Union[str, Sequence[str], None] = 'e2fee546c754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'pdf_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'pdf_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
