"""editors

Revision ID: 908740adb795
Revises: 34ede3b76541
Create Date: 2025-11-20 20:09:14.702328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '908740adb795'
down_revision: Union[str, Sequence[str], None] = '34ede3b76541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editors', sa.Column('full_name', sa.String(), nullable=True))
    op.alter_column('editors', 'prefix',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('editors', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('editors', 'institution',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('editors', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('editors', 'last_name')
    op.drop_column('editors', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editors', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('editors', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('editors', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('editors', 'institution',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('editors', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('editors', 'prefix',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('editors', 'full_name')
    # ### end Alembic commands ###
