"""volume_number

Revision ID: 9ea747adda5c
Revises: 28676ac61a94
Create Date: 2025-08-29 14:31:48.618952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea747adda5c'
down_revision: Union[str, Sequence[str], None] = '28676ac61a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proceeding_volume', sa.Column('volume_number', sa.String(), nullable=False, server_default=""), )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proceeding_volume', 'volume_number')
    # ### end Alembic commands ###
