"""authors fix

Revision ID: a2241b9a1978
Revises: 7e851d742ae3
Create Date: 2025-08-26 15:32:29.545164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2241b9a1978'
down_revision: Union[str, Sequence[str], None] = '7e851d742ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('article_authors_article_id_fkey'), 'article_authors', type_='foreignkey')
    op.drop_constraint(op.f('article_authors_author_id_fkey'), 'article_authors', type_='foreignkey')
    op.create_foreign_key(None, 'article_authors', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'article_authors', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article_authors', type_='foreignkey')
    op.drop_constraint(None, 'article_authors', type_='foreignkey')
    op.create_foreign_key(op.f('article_authors_author_id_fkey'), 'article_authors', 'authors', ['author_id'], ['id'])
    op.create_foreign_key(op.f('article_authors_article_id_fkey'), 'article_authors', 'articles', ['article_id'], ['id'])
    # ### end Alembic commands ###
