"""proceeding_volume

Revision ID: bf9234d67ecb
Revises: eeef05e45d89
Create Date: 2025-08-29 11:45:49.367314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf9234d67ecb'
down_revision: Union[str, Sequence[str], None] = 'eeef05e45d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proceeding_volume',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('total_pages', sa.String(), nullable=False),
    sa.Column('place', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('conference_full_name', sa.String(), nullable=False),
    sa.Column('held_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proceeding_volume_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proceeding_volume_id', sa.String(), nullable=True),
    sa.Column('article_id', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['proceeding_volume_id'], ['proceeding_volume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('proceeding_articles')
    op.drop_table('proceedings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proceedings',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_pages', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('place', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('conference_full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('held_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='proceedings_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('proceeding_articles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('proceeding_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('article_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('proceeding_articles_article_id_fkey')),
    sa.ForeignKeyConstraint(['proceeding_id'], ['proceedings.id'], name=op.f('proceeding_articles_proceeding_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('proceeding_articles_pkey'))
    )
    op.drop_table('proceeding_volume_articles')
    op.drop_table('proceeding_volume')
    # ### end Alembic commands ###
