"""created_at authors

Revision ID: d61bcc5fe71b
Revises: f53b1c51b4df
Create Date: 2025-09-14 18:53:17.096412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd61bcc5fe71b'
down_revision: Union[str, Sequence[str], None] = 'f53b1c51b4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'created_at')
    # ### end Alembic commands ###
