"""articles fix

Revision ID: e2fee546c754
Revises: 571df5b81e4f
Create Date: 2025-08-26 11:00:08.171477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2fee546c754'
down_revision: Union[str, Sequence[str], None] = '571df5b81e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'doi',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('articles', 'doi',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
