"""authors 2

Revision ID: e7e8ccbf5c9f
Revises: 1883b31fc2fd
Create Date: 2025-08-13 13:19:04.237723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e8ccbf5c9f'
down_revision: Union[str, Sequence[str], None] = '1883b31fc2fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('affiliation_clarification_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('authors_affiliation_clarification_fkey'), 'authors', type_='foreignkey')
    op.create_foreign_key(None, 'authors', 'affiliation_clarification', ['affiliation_clarification_id'], ['id'])
    op.drop_column('authors', 'affiliation_clarification')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('affiliation_clarification', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.create_foreign_key(op.f('authors_affiliation_clarification_fkey'), 'authors', 'affiliation_clarification', ['affiliation_clarification'], ['id'])
    op.drop_column('authors', 'affiliation_clarification_id')
    # ### end Alembic commands ###
