"""proceeding volume editors

Revision ID: ea93f5022e5e
Revises: 715e55c6461e
Create Date: 2025-09-04 12:32:07.349731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea93f5022e5e'
down_revision: Union[str, Sequence[str], None] = '715e55c6461e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proceeding_volume_editors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proceeding_volume_id', sa.String(), nullable=True),
    sa.Column('editor_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['editor_id'], ['editors.id'], ),
    sa.ForeignKeyConstraint(['proceeding_volume_id'], ['proceeding_volume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proceeding_volume_editors')
    op.drop_table('editors')
    # ### end Alembic commands ###
