"""proceedings

Revision ID: eeef05e45d89
Revises: 929233a90699
Create Date: 2025-08-29 11:12:45.550230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeef05e45d89'
down_revision: Union[str, Sequence[str], None] = '929233a90699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proceedings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('total_pages', sa.String(), nullable=False),
    sa.Column('place', sa.Text(), nullable=False),
    sa.Column('conference_full_name', sa.String(), nullable=False),
    sa.Column('held_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proceeding_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proceeding_id', sa.String(), nullable=True),
    sa.Column('article_id', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['proceeding_id'], ['proceedings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proceeding_articles')
    op.drop_table('proceedings')
    # ### end Alembic commands ###
