"""created_at at minor changes

Revision ID: f53b1c51b4df
Revises: 4ec2c083003f
Create Date: 2025-09-11 21:15:20.465420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53b1c51b4df'
down_revision: Union[str, Sequence[str], None] = '4ec2c083003f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('articles', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('articles', 'created_at')
    # ### end Alembic commands ###
