/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorsIndexRouteImport } from './routes/authors/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as AffiliationsIndexRouteImport } from './routes/affiliations/index'
import { Route as AuthorsAuthorIdIndexRouteImport } from './routes/authors/$authorId/index'
import { Route as ArticlesArticleIdIndexRouteImport } from './routes/articles/$articleId/index'
import { Route as AffiliationsAffiliationIdIndexRouteImport } from './routes/affiliations/$affiliationId/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliationsIndexRoute = AffiliationsIndexRouteImport.update({
  id: '/affiliations/',
  path: '/affiliations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsAuthorIdIndexRoute = AuthorsAuthorIdIndexRouteImport.update({
  id: '/authors/$authorId/',
  path: '/authors/$authorId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleIdIndexRoute = ArticlesArticleIdIndexRouteImport.update({
  id: '/articles/$articleId/',
  path: '/articles/$articleId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliationsAffiliationIdIndexRoute =
  AffiliationsAffiliationIdIndexRouteImport.update({
    id: '/affiliations/$affiliationId/',
    path: '/affiliations/$affiliationId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliations': typeof AffiliationsIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/authors': typeof AuthorsIndexRoute
  '/affiliations/$affiliationId': typeof AffiliationsAffiliationIdIndexRoute
  '/articles/$articleId': typeof ArticlesArticleIdIndexRoute
  '/authors/$authorId': typeof AuthorsAuthorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliations': typeof AffiliationsIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/authors': typeof AuthorsIndexRoute
  '/affiliations/$affiliationId': typeof AffiliationsAffiliationIdIndexRoute
  '/articles/$articleId': typeof ArticlesArticleIdIndexRoute
  '/authors/$authorId': typeof AuthorsAuthorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliations/': typeof AffiliationsIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/authors/': typeof AuthorsIndexRoute
  '/affiliations/$affiliationId/': typeof AffiliationsAffiliationIdIndexRoute
  '/articles/$articleId/': typeof ArticlesArticleIdIndexRoute
  '/authors/$authorId/': typeof AuthorsAuthorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliations'
    | '/articles'
    | '/authors'
    | '/affiliations/$affiliationId'
    | '/articles/$articleId'
    | '/authors/$authorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliations'
    | '/articles'
    | '/authors'
    | '/affiliations/$affiliationId'
    | '/articles/$articleId'
    | '/authors/$authorId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affiliations/'
    | '/articles/'
    | '/authors/'
    | '/affiliations/$affiliationId/'
    | '/articles/$articleId/'
    | '/authors/$authorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffiliationsIndexRoute: typeof AffiliationsIndexRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  AuthorsIndexRoute: typeof AuthorsIndexRoute
  AffiliationsAffiliationIdIndexRoute: typeof AffiliationsAffiliationIdIndexRoute
  ArticlesArticleIdIndexRoute: typeof ArticlesArticleIdIndexRoute
  AuthorsAuthorIdIndexRoute: typeof AuthorsAuthorIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/': {
      id: '/authors/'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliations/': {
      id: '/affiliations/'
      path: '/affiliations'
      fullPath: '/affiliations'
      preLoaderRoute: typeof AffiliationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$authorId/': {
      id: '/authors/$authorId/'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthorsAuthorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleId/': {
      id: '/articles/$articleId/'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof ArticlesArticleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliations/$affiliationId/': {
      id: '/affiliations/$affiliationId/'
      path: '/affiliations/$affiliationId'
      fullPath: '/affiliations/$affiliationId'
      preLoaderRoute: typeof AffiliationsAffiliationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffiliationsIndexRoute: AffiliationsIndexRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
  AffiliationsAffiliationIdIndexRoute: AffiliationsAffiliationIdIndexRoute,
  ArticlesArticleIdIndexRoute: ArticlesArticleIdIndexRoute,
  AuthorsAuthorIdIndexRoute: AuthorsAuthorIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
